/*
 * Kibi — repo-local, per-branch, queryable long-term memory for software projects
 * Copyright (C) 2026 Piotr Franczyk
 *
 * This file is generated by scripts/generate-rule-registry.mjs from
 * packages/core/schema/rule-registry.json. Do not edit it directly; edit the
 * JSON source and regenerate.
 */

// implements REQ-006
/** Every selectable kb_check rule name, registry order. */
export const SELECTABLE_RULE_NAMES: readonly string[] = [
  "must-priority-coverage",
  "symbol-coverage",
  "symbol-traceability",
  "no-dangling-refs",
  "source-relationship-parity",
  "no-cycles",
  "required-fields",
  "deprecated-adr-no-successor",
  "domain-contradictions",
  "logic-coverage",
  "rule-safety",
  "rule-verifiability",
  "query-plan-safety",
  "req-status-vocabulary",
  "strict-fact-shape",
  "strict-req-fact-pairing",
  "predicate-verifiability",
  "strict-readiness",
  "semantic-completeness",
];

// implements REQ-006
/** Comma-separated "Allowed:" fragment for the kb_check rules description. */
export const SELECTABLE_RULES_ALLOWED = "must-priority-coverage, symbol-coverage, symbol-traceability, no-dangling-refs, source-relationship-parity, no-cycles, required-fields, deprecated-adr-no-successor, domain-contradictions, logic-coverage, rule-safety, rule-verifiability, query-plan-safety, req-status-vocabulary, strict-fact-shape, strict-req-fact-pairing, predicate-verifiability, strict-readiness, semantic-completeness";
