/*
 * Kibi — repo-local, per-branch, queryable long-term memory for software projects
 * Copyright (C) 2026 Piotr Franczyk
 *
 * This file is generated by scripts/generate-rule-registry.mjs from
 * packages/core/schema/rule-registry.json. Do not edit it directly; edit the
 * JSON source and regenerate.
 */

// implements REQ-006
/** Every selectable kb_check rule name, registry order. */
export const SELECTABLE_RULE_NAMES: readonly string[] = [
  "must-priority-coverage",
  "symbol-coverage",
  "symbol-traceability",
  "no-dangling-refs",
  "source-relationship-parity",
  "branch-store-not-compiled",
  "source-path-dangling",
  "no-cycles",
  "required-fields",
  "deprecated-adr-no-successor",
  "superseded-requirement-open",
  "scenario-feasibility",
  "scenario-feasibility-unknown",
  "exception-claim-keys",
  "numeric-string-value",
  "rule-key-arguments-missing",
  "domain-contradictions",
  "logic-coverage",
  "rule-safety",
  "rule-verifiability",
  "query-plan-safety",
  "req-status-vocabulary",
  "strict-fact-shape",
  "strict-req-fact-pairing",
  "predicate-verifiability",
  "strict-readiness",
  "semantic-completeness",
  "related-requirement-unmodeled",
  "proof-contract-symbols",
  "entity-id-style",
  "domain-redundancy",
  "domain-implication",
  "subject-key-identity",
  "subject-key-shape",
  "ontology-quality",
  "exception-unapproved",
  "exception-approval-self-attested",
  "agent-requirement-unapproved",
  "requirement-rationale-missing",
  "symbol-owner-superseded",
  "adr-unlinked",
  "adr-proposed",
  "predicate-schema-conformance",
  "entity-context-missing",
  "entity-context-acknowledged",
  "policy-ownership",
  "policy-markers",
];

// implements REQ-006
/** Comma-separated "Allowed:" fragment for the kb_check rules description. */
export const SELECTABLE_RULES_ALLOWED =
  "must-priority-coverage, symbol-coverage, symbol-traceability, no-dangling-refs, source-relationship-parity, branch-store-not-compiled, source-path-dangling, no-cycles, required-fields, deprecated-adr-no-successor, superseded-requirement-open, scenario-feasibility, scenario-feasibility-unknown, exception-claim-keys, numeric-string-value, rule-key-arguments-missing, domain-contradictions, logic-coverage, rule-safety, rule-verifiability, query-plan-safety, req-status-vocabulary, strict-fact-shape, strict-req-fact-pairing, predicate-verifiability, strict-readiness, semantic-completeness, related-requirement-unmodeled, proof-contract-symbols, entity-id-style, domain-redundancy, domain-implication, subject-key-identity, subject-key-shape, ontology-quality, exception-unapproved, exception-approval-self-attested, agent-requirement-unapproved, requirement-rationale-missing, symbol-owner-superseded, adr-unlinked, adr-proposed, predicate-schema-conformance, entity-context-missing, entity-context-acknowledged, policy-ownership, policy-markers";
