/**
 * build-agent-plugin.ts
 *
 * Generates the portable Agent Plugins (agent-plugins.org) artifact for Kibi
 * under `packages/cursor/agent-plugin/`:
 *
 *   agent-plugin/
 *   ├── plugin.json   — Agent Plugins 1.0.0 manifest
 *   ├── skills/       — canonical Agent Skills mirror (same source as the
 *   │                   Cursor and Codex mirrors)
 *   └── mcp.json      — Agent Plugins-compliant stdio MCP server config
 *
 * The Agent Plugins open standard packages portable Agent Skills and MCP
 * servers. Cursor-only components (rules, commands, hooks) stay in the
 * `.cursor-plugin` Cursor Plugin format. The artifact is committed so a fresh
 * marketplace clone resolves it without a build step.
 */
// allow: SIZE_OK — the artifact is small and regenerated atomically.
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const EXPECTED_SKILL_IDS = [
  "kibi-bootstrap",
  "kibi-freshness",
  "kibi-traceability",
  "kibi-usage",
] as const;

const AGENT_PLUGIN_SCHEMA =
  "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json";
const AGENT_MCP_SCHEMA =
  "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json";

interface PackageJson {
  name?: string;
  version?: string;
  description?: string;
  license?: string;
  homepage?: string;
  repository?: string | { url?: string };
}

function repoRootFromScript(): string {
  const here = dirname(fileURLToPath(import.meta.url));
  return resolve(here, "../../..");
}

function canonicalSkillsDir(repoRoot: string): string {
  return resolve(repoRoot, "packages/cli/src/public/skills");
}

function cursorPackageRoot(repoRoot: string): string {
  return resolve(repoRoot, "packages/cursor");
}

function agentPluginRoot(repoRoot: string): string {
  return resolve(cursorPackageRoot(repoRoot), "agent-plugin");
}

function readJson<T>(filePath: string): T {
  return JSON.parse(readFileSync(filePath, "utf8")) as T;
}

const AGENT_JSON_LINE_WIDTH = 80;

// Serializes a manifest value the way the repo's biome formatter prints JSON:
// 2-space indentation, `": "` / `", "` separators, and single-line containers
// when they fit within the line width at their current column. The committed
// artifact is regenerated by this script, so keeping its output biome-clean
// keeps `bun run check` green after every `build:cursor`.
function singleLineAgentJson(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) {
    return `[${value.map((item) => singleLineAgentJson(item)).join(", ")}]`;
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>);
    return `{ ${entries
      .map(
        ([key, item]) => `${JSON.stringify(key)}: ${singleLineAgentJson(item)}`,
      )
      .join(", ")} }`;
  }
  return JSON.stringify(value);
}

function formatAgentJson(
  value: unknown,
  column: number,
  depth: number,
): string {
  if (value === null || typeof value !== "object") {
    return JSON.stringify(value);
  }
  const single = singleLineAgentJson(value);
  if (column + single.length <= AGENT_JSON_LINE_WIDTH) {
    return single;
  }
  const pad = " ".repeat(depth * 2);
  const itemPad = " ".repeat((depth + 1) * 2);
  if (Array.isArray(value)) {
    const items = value.map((item) =>
      formatAgentJson(item, column + 2, depth + 1),
    );
    return `[\n${items.map((item) => `${itemPad}${item}`).join(",\n")}\n${pad}]`;
  }
  const entries = Object.entries(value as Record<string, unknown>);
  const parts = entries.map(([key, item]) => {
    const prefix = `${JSON.stringify(key)}: `;
    return `${itemPad}${prefix}${formatAgentJson(item, column + 2 + prefix.length, depth + 1)}`;
  });
  return `{\n${parts.join(",\n")}\n${pad}}`;
}

function formatAgentJsonDocument(value: unknown): string {
  return `${formatAgentJson(value, 0, 0)}\n`;
}

function walkFiles(rootDir: string): string[] {
  const out: string[] = [];
  const stack: string[] = [rootDir];
  while (stack.length > 0) {
    const current = stack.pop();
    if (current === undefined) break;
    for (const entry of readdirSync(current, { withFileTypes: true })) {
      const full = join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(full);
      } else if (entry.isFile()) {
        out.push(full);
      }
    }
  }
  return out.sort();
}

function assertCanonicalSourceComplete(canonicalRoot: string): void {
  if (!existsSync(canonicalRoot)) {
    throw new Error(
      `Canonical skills source missing: ${canonicalRoot}. Run this script from the kibi repo root.`,
    );
  }
  for (const id of EXPECTED_SKILL_IDS) {
    const skillFile = join(canonicalRoot, id, "SKILL.md");
    if (!existsSync(skillFile)) {
      throw new Error(
        `Canonical skill ${id} is missing its SKILL.md at ${skillFile}`,
      );
    }
  }
}

function planSkillMirror(
  canonicalRoot: string,
  skillId: string,
): ReadonlyArray<{ relPath: string; content: Buffer }> {
  const skillRoot = join(canonicalRoot, skillId);
  return walkFiles(skillRoot).map((absoluteSource) => ({
    relPath: `${skillId}/${relative(skillRoot, absoluteSource).split("\\").join("/")}`,
    content: readFileSync(absoluteSource),
  }));
}

function writeSkillsMirror(repoRoot: string, targetRoot: string): void {
  const canonicalRoot = canonicalSkillsDir(repoRoot);
  assertCanonicalSourceComplete(canonicalRoot);
  const skillsRoot = join(targetRoot, "skills");
  rmSync(skillsRoot, { recursive: true, force: true });
  mkdirSync(skillsRoot, { recursive: true });
  for (const id of EXPECTED_SKILL_IDS) {
    for (const file of planSkillMirror(canonicalRoot, id)) {
      const target = join(skillsRoot, file.relPath);
      mkdirSync(dirname(target), { recursive: true });
      writeFileSync(target, file.content);
    }
  }
}

function buildAgentPluginMcpJson(repoRoot: string): object {
  const cursorMcpPath = join(cursorPackageRoot(repoRoot), "mcp.json");
  if (!existsSync(cursorMcpPath)) {
    throw new Error(
      `Missing Cursor MCP config at ${cursorMcpPath}; cannot derive the Agent Plugin mcp.json.`,
    );
  }
  const cursorMcp = readJson<{ mcpServers?: Record<string, object> }>(
    cursorMcpPath,
  );
  const mcpServers = cursorMcp.mcpServers ?? {};
  const normalizedServers: Record<string, object> = {};
  for (const [name, server] of Object.entries(mcpServers)) {
    normalizedServers[name] = { type: "stdio", ...(server as object) };
  }
  return { $schema: AGENT_MCP_SCHEMA, mcpServers: normalizedServers };
}

function repositoryUrl(packageJson: PackageJson): string {
  const repo = packageJson.repository;
  if (typeof repo === "string") return repo;
  if (repo !== null && typeof repo === "object" && "url" in repo) {
    return String(repo.url);
  }
  return "https://github.com/Looted/kibi";
}

function buildPluginManifest(packageJson: PackageJson): object {
  return {
    $schema: AGENT_PLUGIN_SCHEMA,
    name: "kibi",
    version: packageJson.version ?? "0.0.0",
    description:
      "Repo-local, per-branch, queryable knowledge base. Portable Agent Plugin packaging Kibi's Agent Skills and MCP server.",
    author: { name: "Kibi" },
    homepage:
      packageJson.homepage ??
      "https://github.com/Looted/kibi/blob/develop/docs/install.md",
    repository: repositoryUrl(packageJson),
    license: packageJson.license ?? "AGPL-3.0-or-later",
    keywords: ["kibi", "mcp", "knowledge-base", "traceability", "swi-prolog"],
  };
}

export function buildAgentPluginUnlocked(
  repoRoot: string,
  targetRoot?: string,
): string {
  const resolvedTarget = targetRoot ?? agentPluginRoot(repoRoot);
  rmSync(resolvedTarget, { recursive: true, force: true });
  mkdirSync(resolvedTarget, { recursive: true });

  const packageJson = readJson<PackageJson>(
    join(cursorPackageRoot(repoRoot), "package.json"),
  );

  writeSkillsMirror(repoRoot, resolvedTarget);
  writeFileSync(
    join(resolvedTarget, "mcp.json"),
    formatAgentJsonDocument(buildAgentPluginMcpJson(repoRoot)),
  );
  writeFileSync(
    join(resolvedTarget, "plugin.json"),
    formatAgentJsonDocument(buildPluginManifest(packageJson)),
  );

  return resolvedTarget;
}

async function main(argv: string[]): Promise<void> {
  for (const arg of argv) {
    if (arg === "--write") continue;
    process.stderr.write(`build-agent-plugin: unknown flag: ${arg}\n`);
    process.exit(2);
  }
  const repoRoot = repoRootFromScript();
  try {
    const targetRoot = buildAgentPluginUnlocked(repoRoot);
    process.stdout.write(
      `build-agent-plugin: wrote Agent Plugin artifact to ${targetRoot}\n`,
    );
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`build-agent-plugin: ${message}\n`);
    process.exit(1);
  }
}

const args = process.argv.slice(2);
const invokedDirectly =
  process.argv[1] !== undefined &&
  resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (invokedDirectly) {
  await main(args);
}

export {
  AGENT_MCP_SCHEMA,
  AGENT_PLUGIN_SCHEMA,
  EXPECTED_SKILL_IDS,
  agentPluginRoot,
  buildAgentPluginMcpJson,
  buildPluginManifest,
};
