coverage:
  precision: 2
  round: down
  range: "50...100"
  status:
    project:
      unit:
        target: 50%
        threshold: 0%
        flags:
          - unit
    patch:
      unit:
        target: 100%
        threshold: 0%
        flags:
          - unit
