// Generated by scripts/qualify-source-analyzers.mjs after release qualification.
// Do not approve changed bytes without reviewing the executable and asset closure.
// implements REQ-source-analysis-v2
export const qualifiedSourceAnalyzers = [
  {
    packageName: "kibi-plugin-treesitter",
    version: "0.1.2",
    files: {
      "SBOM.spdx.json":
        "55bc42e9b7776a5b8212f4a5eda7269a2ca25dd5213043124d073f6f26f74148",
      "THIRD_PARTY_NOTICES.md":
        "6a9736302ea4d0687eabfdaa9d4aba9ab182f0e50cf00c812bbf763fd1b8eb97",
      "assets/queries/go.scm":
        "d1a9b1f678fe0278b85054e2dc56a28ef26aa478b8c88fb2b0dd83cdcdb9db35",
      "assets/queries/python.scm":
        "d0f3e577878167bfabc30e526e497bce58d1699b9bcabf8ab3a50698efb5ca3e",
      "assets/queries/rust-extra.scm":
        "511a492200e813f15b7ebec324eae69a245986a9d6813ddabe776075fd65976c",
      "assets/queries/rust.scm":
        "f22867fdebde5cb091861c08d34690dc2540f4318068bf81be9f6b0d348ab8c1",
      "assets/tree-sitter-go.wasm":
        "9504573f352b20be7f2f1911754d710622aedc15afff16d5ed8fb5645681aee7",
      "assets/tree-sitter-python.wasm":
        "16108b50df4ee9a30168794252ab55e7c93bfc5765d7fa0aa3e335752c515f47",
      "assets/tree-sitter-rust.wasm":
        "f65f354215611fd94ad34134b3427eb3d58cbb745df7b6509ba722184db73d57",
      "catalog.json":
        "239ae4201dfa147a26fa5d19ea995b8d00c3c72114997c7e6bebf2918be464c8",
      "dist/analysis-worker.js":
        "59404246864a2d91ceceab64f3ff0ee89ee6c275b1cfddb08c3bfaa1a0e6064e",
      "dist/catalog.js":
        "f968a2bae1da2d7fc17f915728d419a85d558fb0c4e72baa236633b309a66ae0",
      "dist/extractor.js":
        "420eb0861c90a869fef2472bb5bdbc758383dbc47b1aa42174b6dc289704f441",
      "dist/index.js":
        "adc03d77d94c0133b3188950b35f79db19e447cf7bfa1f7e1cf1f5c97a582a44",
      "integrity.json":
        "fcc5a29bef0697e3e8ba60a04a32ddf35c63538908369addf324d65fd0ac4d7e",
      "licenses/tree-sitter-go-MIT.txt":
        "2e0110e07abef7c2548b26ec9d6969775617ca539a0dc8dbeeb14d6452c711d1",
      "licenses/tree-sitter-python-MIT.txt":
        "d724405ce238a22c0d35769c5a36b386ad5958192efe8bbb304fb2896254575f",
      "licenses/tree-sitter-rust-MIT.txt":
        "31d5b6f4243d5c7c6e1c4ebbbb9f6407bd1457a08bcc4f706521710341acba36",
      "licenses/web-tree-sitter-MIT.txt":
        "c5cfb43042b6b72045f4ba997834d0a7786d2793d91680868b5815b39f14fc78",
      "package.json":
        "1a402e94d0d93fd37111a854f275eaeb2c340af24141e062a6da2864e500aeea",
    },
    dependencies: [
      {
        packageName: "web-tree-sitter",
        version: "0.27.0",
        files: {
          LICENSE:
            "c5cfb43042b6b72045f4ba997834d0a7786d2793d91680868b5815b39f14fc78",
          "debug/web-tree-sitter.cjs":
            "3faca4a6e5a006ec8e95a8e1918923ee9a385a02f64154fb2a893d5a27200f24",
          "debug/web-tree-sitter.js":
            "4cd02f4b5510044807279f7064e6bcceab391af3c245fc9b6da2de7b1116ff84",
          "debug/web-tree-sitter.wasm":
            "91a157f507fabb836588e6537a1af1bae45d3d4b9278d06d003678460b011d8e",
          "package.json":
            "707dd14277ba63ca8dcaad6b6df8051e23df78c878b5cbdc27885b3cfd72bfac",
          "web-tree-sitter.cjs":
            "743de33347202f863b6714fc7218c455d93f751943d43500500f6c5c65654dce",
          "web-tree-sitter.js":
            "7c49e3c1d87e24e0bb4c2def909d17154dfde281f5f8280225450090bb4b8110",
          "web-tree-sitter.wasm":
            "c03bccdc3b448a32848f5ae327e209c982bbb0840d43eec8bc2d5759544a1ed3",
        },
      },
    ],
  },
] as const;
