% Module: rule_registry
% GENERATED by scripts/generate-rule-registry.mjs from
% packages/core/schema/rule-registry.json. Do not edit directly.
%
% Registry facts shared by TS and Prolog so unknown rule names fail loudly
% instead of silently returning empty results.

:- module(rule_registry, [
    known_rule/1,
    rule_enforcement_class/2,
    rule_implementation/2,
    rule_predicate/2,
    rule_predicate_arity/2,
    rule_description/2
]).

known_rule('must-priority-coverage').
known_rule('symbol-coverage').
known_rule('symbol-traceability').
known_rule('no-dangling-refs').
known_rule('source-relationship-parity').
known_rule('no-cycles').
known_rule('required-fields').
known_rule('deprecated-adr-no-successor').
known_rule('domain-contradictions').
known_rule('logic-coverage').
known_rule('rule-safety').
known_rule('rule-verifiability').
known_rule('query-plan-safety').
known_rule('req-status-vocabulary').
known_rule('strict-fact-shape').
known_rule('strict-req-fact-pairing').
known_rule('predicate-verifiability').
known_rule('strict-readiness').
known_rule('semantic-completeness').

rule_enforcement_class('must-priority-coverage', canonical).
rule_enforcement_class('symbol-coverage', canonical).
rule_enforcement_class('symbol-traceability', canonical).
rule_enforcement_class('no-dangling-refs', canonical).
rule_enforcement_class('source-relationship-parity', canonical).
rule_enforcement_class('no-cycles', canonical).
rule_enforcement_class('required-fields', canonical).
rule_enforcement_class('deprecated-adr-no-successor', canonical).
rule_enforcement_class('domain-contradictions', canonical).
rule_enforcement_class('logic-coverage', canonical).
rule_enforcement_class('rule-safety', canonical).
rule_enforcement_class('rule-verifiability', canonical).
rule_enforcement_class('query-plan-safety', canonical).
rule_enforcement_class('req-status-vocabulary', canonical).
rule_enforcement_class('strict-fact-shape', advisory).
rule_enforcement_class('strict-req-fact-pairing', advisory).
rule_enforcement_class('predicate-verifiability', advisory).
rule_enforcement_class('strict-readiness', migration).
rule_enforcement_class('semantic-completeness', migration).

rule_implementation('must-priority-coverage', prolog).
rule_implementation('symbol-coverage', prolog).
rule_implementation('symbol-traceability', prolog).
rule_implementation('no-dangling-refs', prolog).
rule_implementation('source-relationship-parity', typescript).
rule_implementation('no-cycles', prolog).
rule_implementation('required-fields', prolog).
rule_implementation('deprecated-adr-no-successor', prolog).
rule_implementation('domain-contradictions', prolog).
rule_implementation('logic-coverage', prolog).
rule_implementation('rule-safety', prolog).
rule_implementation('rule-verifiability', prolog).
rule_implementation('query-plan-safety', typescript).
rule_implementation('req-status-vocabulary', prolog).
rule_implementation('strict-fact-shape', prolog).
rule_implementation('strict-req-fact-pairing', prolog).
rule_implementation('predicate-verifiability', prolog).
rule_implementation('strict-readiness', prolog).
rule_implementation('semantic-completeness', prolog).

rule_predicate('must-priority-coverage', check_must_priority_coverage).
rule_predicate('symbol-coverage', check_symbol_coverage).
rule_predicate('symbol-traceability', check_symbol_traceability).
rule_predicate('no-dangling-refs', check_no_dangling_refs).
rule_predicate('no-cycles', check_no_cycles).
rule_predicate('required-fields', check_required_fields).
rule_predicate('deprecated-adr-no-successor', check_deprecated_adrs).
rule_predicate('domain-contradictions', check_domain_contradictions).
rule_predicate('logic-coverage', check_logic_coverage).
rule_predicate('rule-safety', check_rule_safety).
rule_predicate('rule-verifiability', check_rule_verifiability).
rule_predicate('req-status-vocabulary', check_req_status_vocabulary).
rule_predicate('strict-fact-shape', check_strict_fact_shape).
rule_predicate('strict-req-fact-pairing', check_strict_req_fact_pairing).
rule_predicate('predicate-verifiability', check_predicate_verifiability).
rule_predicate('strict-readiness', check_strict_readiness).
rule_predicate('semantic-completeness', check_semantic_completeness).

rule_predicate_arity('must-priority-coverage', 1).
rule_predicate_arity('symbol-coverage', 1).
rule_predicate_arity('symbol-traceability', 2).
rule_predicate_arity('no-dangling-refs', 1).
rule_predicate_arity('no-cycles', 1).
rule_predicate_arity('required-fields', 1).
rule_predicate_arity('deprecated-adr-no-successor', 1).
rule_predicate_arity('domain-contradictions', 1).
rule_predicate_arity('logic-coverage', 1).
rule_predicate_arity('rule-safety', 1).
rule_predicate_arity('rule-verifiability', 1).
rule_predicate_arity('req-status-vocabulary', 1).
rule_predicate_arity('strict-fact-shape', 1).
rule_predicate_arity('strict-req-fact-pairing', 1).
rule_predicate_arity('predicate-verifiability', 1).
rule_predicate_arity('strict-readiness', 1).
rule_predicate_arity('semantic-completeness', 1).

rule_description('must-priority-coverage', 'Every must-priority requirement must have a scenario and a test').
rule_description('symbol-coverage', 'Production symbols need qualifying coverage via covered_by plus a canonical requirement/scenario test path').
rule_description('symbol-traceability', 'Production symbols must directly implement requirements for ownership; covered_by is coverage only and executable_for is test identity only').
rule_description('no-dangling-refs', 'All relationship targets must exist in the KB').
rule_description('source-relationship-parity', 'Authored Markdown and relationship-shard edges must exactly match the compiled KB').
rule_description('no-cycles', 'No circular dependency chains in requirements').
rule_description('required-fields', 'All entities must have required fields').
rule_description('deprecated-adr-no-successor', 'Deprecated ADRs must have a successor ADR that supersedes them').
rule_description('domain-contradictions', 'Detect contradictions between requirements constraining the same fact').
rule_description('logic-coverage', 'Require every explicitly declared atomic requirement claim to be grounded by a linked strict-property or predicate fact').
rule_description('rule-safety', 'Stored Logic IR rules use only the typed, bounded, stratified vocabulary').
rule_description('rule-verifiability', 'Requirement rule links resolve to safe rules and registered rule schemas').
rule_description('query-plan-safety', 'Detect Prolog validation clauses that place negation before generator calls').
rule_description('req-status-vocabulary', 'Requirement statuses must use the canonical vocabulary (open, in_progress, closed; legacy: active, approved); ADR statuses such as accepted silently fall out of the proof ladder').
rule_description('strict-fact-shape', 'Detect malformed strict facts (facts with fact_kind that are missing required fields)').
rule_description('strict-req-fact-pairing', 'Detect requirements with incomplete strict subject/property fact pairing for contradiction-safe semantics').
rule_description('predicate-verifiability', 'Detect requires_predicate links that do not target ground fact_kind: predicate facts').
rule_description('strict-readiness', 'Report strict contradiction-readiness levels for requirements that are still prose-only or otherwise not contradiction-ready').
rule_description('semantic-completeness', 'Every inventoried assertive proposition is modeled or explicitly classified').
