% Module: rule_registry
% GENERATED by scripts/generate-rule-registry.mjs from
% packages/core/schema/rule-registry.json. Do not edit directly.
%
% Registry facts shared by TS and Prolog so unknown rule names fail loudly
% instead of silently returning empty results.

:- module(rule_registry, [
    known_rule/1,
    rule_enforcement_class/2,
    rule_implementation/2,
    rule_predicate/2,
    rule_predicate_arity/2,
    rule_description/2
]).

known_rule('must-priority-coverage').
known_rule('symbol-coverage').
known_rule('symbol-traceability').
known_rule('no-dangling-refs').
known_rule('source-relationship-parity').
known_rule('no-cycles').
known_rule('required-fields').
known_rule('deprecated-adr-no-successor').
known_rule('scenario-feasibility').
known_rule('scenario-feasibility-unknown').
known_rule('exception-claim-keys').
known_rule('numeric-string-value').
known_rule('rule-key-arguments-missing').
known_rule('domain-contradictions').
known_rule('logic-coverage').
known_rule('rule-safety').
known_rule('rule-verifiability').
known_rule('query-plan-safety').
known_rule('req-status-vocabulary').
known_rule('strict-fact-shape').
known_rule('strict-req-fact-pairing').
known_rule('predicate-verifiability').
known_rule('strict-readiness').
known_rule('semantic-completeness').
known_rule('proof-contract-symbols').
known_rule('entity-id-style').
known_rule('domain-redundancy').
known_rule('domain-implication').
known_rule('subject-key-identity').
known_rule('subject-key-shape').
known_rule('ontology-quality').
known_rule('exception-unapproved').
known_rule('exception-approval-self-attested').
known_rule('agent-requirement-unapproved').
known_rule('predicate-schema-conformance').

rule_enforcement_class('must-priority-coverage', canonical).
rule_enforcement_class('symbol-coverage', canonical).
rule_enforcement_class('symbol-traceability', canonical).
rule_enforcement_class('no-dangling-refs', canonical).
rule_enforcement_class('source-relationship-parity', canonical).
rule_enforcement_class('no-cycles', canonical).
rule_enforcement_class('required-fields', canonical).
rule_enforcement_class('deprecated-adr-no-successor', canonical).
rule_enforcement_class('scenario-feasibility', canonical).
rule_enforcement_class('scenario-feasibility-unknown', advisory).
rule_enforcement_class('exception-claim-keys', canonical).
rule_enforcement_class('numeric-string-value', advisory).
rule_enforcement_class('rule-key-arguments-missing', advisory).
rule_enforcement_class('domain-contradictions', canonical).
rule_enforcement_class('logic-coverage', canonical).
rule_enforcement_class('rule-safety', canonical).
rule_enforcement_class('rule-verifiability', canonical).
rule_enforcement_class('query-plan-safety', canonical).
rule_enforcement_class('req-status-vocabulary', canonical).
rule_enforcement_class('strict-fact-shape', advisory).
rule_enforcement_class('strict-req-fact-pairing', advisory).
rule_enforcement_class('predicate-verifiability', advisory).
rule_enforcement_class('strict-readiness', migration).
rule_enforcement_class('semantic-completeness', migration).
rule_enforcement_class('proof-contract-symbols', advisory).
rule_enforcement_class('entity-id-style', advisory).
rule_enforcement_class('domain-redundancy', advisory).
rule_enforcement_class('domain-implication', advisory).
rule_enforcement_class('subject-key-identity', advisory).
rule_enforcement_class('subject-key-shape', advisory).
rule_enforcement_class('ontology-quality', advisory).
rule_enforcement_class('exception-unapproved', advisory).
rule_enforcement_class('exception-approval-self-attested', advisory).
rule_enforcement_class('agent-requirement-unapproved', advisory).
rule_enforcement_class('predicate-schema-conformance', advisory).

rule_implementation('must-priority-coverage', prolog).
rule_implementation('symbol-coverage', prolog).
rule_implementation('symbol-traceability', prolog).
rule_implementation('no-dangling-refs', prolog).
rule_implementation('source-relationship-parity', typescript).
rule_implementation('no-cycles', prolog).
rule_implementation('required-fields', prolog).
rule_implementation('deprecated-adr-no-successor', prolog).
rule_implementation('scenario-feasibility', prolog).
rule_implementation('scenario-feasibility-unknown', prolog).
rule_implementation('exception-claim-keys', prolog).
rule_implementation('numeric-string-value', prolog).
rule_implementation('rule-key-arguments-missing', prolog).
rule_implementation('domain-contradictions', prolog).
rule_implementation('logic-coverage', prolog).
rule_implementation('rule-safety', prolog).
rule_implementation('rule-verifiability', prolog).
rule_implementation('query-plan-safety', typescript).
rule_implementation('req-status-vocabulary', prolog).
rule_implementation('strict-fact-shape', prolog).
rule_implementation('strict-req-fact-pairing', prolog).
rule_implementation('predicate-verifiability', prolog).
rule_implementation('strict-readiness', prolog).
rule_implementation('semantic-completeness', prolog).
rule_implementation('proof-contract-symbols', prolog).
rule_implementation('entity-id-style', prolog).
rule_implementation('domain-redundancy', prolog).
rule_implementation('domain-implication', prolog).
rule_implementation('subject-key-identity', prolog).
rule_implementation('subject-key-shape', prolog).
rule_implementation('ontology-quality', prolog).
rule_implementation('exception-unapproved', typescript).
rule_implementation('exception-approval-self-attested', typescript).
rule_implementation('agent-requirement-unapproved', typescript).
rule_implementation('predicate-schema-conformance', typescript).

rule_predicate('must-priority-coverage', check_must_priority_coverage).
rule_predicate('symbol-coverage', check_symbol_coverage).
rule_predicate('symbol-traceability', check_symbol_traceability).
rule_predicate('no-dangling-refs', check_no_dangling_refs).
rule_predicate('no-cycles', check_no_cycles).
rule_predicate('required-fields', check_required_fields).
rule_predicate('deprecated-adr-no-successor', check_deprecated_adrs).
rule_predicate('scenario-feasibility', check_scenario_feasibility).
rule_predicate('scenario-feasibility-unknown', check_scenario_feasibility_unknown).
rule_predicate('exception-claim-keys', check_exception_claim_keys).
rule_predicate('numeric-string-value', check_numeric_string_values).
rule_predicate('rule-key-arguments-missing', check_rule_key_arguments_missing).
rule_predicate('domain-contradictions', check_domain_contradictions).
rule_predicate('logic-coverage', check_logic_coverage).
rule_predicate('rule-safety', check_rule_safety).
rule_predicate('rule-verifiability', check_rule_verifiability).
rule_predicate('req-status-vocabulary', check_req_status_vocabulary).
rule_predicate('strict-fact-shape', check_strict_fact_shape).
rule_predicate('strict-req-fact-pairing', check_strict_req_fact_pairing).
rule_predicate('predicate-verifiability', check_predicate_verifiability).
rule_predicate('strict-readiness', check_strict_readiness).
rule_predicate('semantic-completeness', check_semantic_completeness).
rule_predicate('proof-contract-symbols', check_proof_contract_symbols).
rule_predicate('entity-id-style', check_entity_id_style).
rule_predicate('domain-redundancy', check_domain_redundancy).
rule_predicate('domain-implication', check_domain_implication).
rule_predicate('subject-key-identity', check_subject_key_identity).
rule_predicate('subject-key-shape', check_subject_key_shape).
rule_predicate('ontology-quality', check_ontology_quality).

rule_predicate_arity('must-priority-coverage', 1).
rule_predicate_arity('symbol-coverage', 1).
rule_predicate_arity('symbol-traceability', 2).
rule_predicate_arity('no-dangling-refs', 1).
rule_predicate_arity('no-cycles', 1).
rule_predicate_arity('required-fields', 1).
rule_predicate_arity('deprecated-adr-no-successor', 1).
rule_predicate_arity('scenario-feasibility', 1).
rule_predicate_arity('scenario-feasibility-unknown', 1).
rule_predicate_arity('exception-claim-keys', 1).
rule_predicate_arity('numeric-string-value', 1).
rule_predicate_arity('rule-key-arguments-missing', 1).
rule_predicate_arity('domain-contradictions', 1).
rule_predicate_arity('logic-coverage', 1).
rule_predicate_arity('rule-safety', 1).
rule_predicate_arity('rule-verifiability', 1).
rule_predicate_arity('req-status-vocabulary', 1).
rule_predicate_arity('strict-fact-shape', 1).
rule_predicate_arity('strict-req-fact-pairing', 1).
rule_predicate_arity('predicate-verifiability', 1).
rule_predicate_arity('strict-readiness', 1).
rule_predicate_arity('semantic-completeness', 1).
rule_predicate_arity('proof-contract-symbols', 1).
rule_predicate_arity('entity-id-style', 1).
rule_predicate_arity('domain-redundancy', 1).
rule_predicate_arity('domain-implication', 1).
rule_predicate_arity('subject-key-identity', 1).
rule_predicate_arity('subject-key-shape', 1).
rule_predicate_arity('ontology-quality', 1).

rule_description('must-priority-coverage', 'Every must-priority requirement must have a scenario and a test').
rule_description('symbol-coverage', 'Production symbols need qualifying coverage via covered_by plus a canonical requirement/scenario test path').
rule_description('symbol-traceability', 'Production symbols must directly implement requirements for ownership; covered_by is coverage only and executable_for is test identity only').
rule_description('no-dangling-refs', 'All relationship targets must exist in the KB').
rule_description('source-relationship-parity', 'Authored Markdown and relationship-shard edges must exactly match the compiled KB').
rule_description('no-cycles', 'No circular dependency chains in requirements').
rule_description('required-fields', 'All entities must have required fields').
rule_description('deprecated-adr-no-successor', 'Deprecated ADRs must have a successor ADR that supersedes them').
rule_description('scenario-feasibility', 'A scenario that expects success must not assume property values that cannot hold, alone or together, with what current requirements require through typed property values or rules, unless an approved exception requirement waives that requirement or the listed clauses').
rule_description('scenario-feasibility-unknown', 'Advisory: a scenario that expects success assumes nothing, assumes values that contradict each other, assumes a property value no governing requirement constrains comparably (type, unit or operator mismatch, or conflicting requirements), leaves a governing rule\'s conditions undecided, or conflicts only with constraints whose validity window may not cover it, so its feasibility cannot be decided').
rule_description('exception-claim-keys', 'An exception requirement\'s exempts_claims must name claim keys of a requirement it exempts, and requires an exempts link').
rule_description('numeric-string-value', 'Advisory: a property value stores a numeric-looking string where the comparison is numeric (ordering operator, or an int/number fact on the same property); the finding names the fact and the typed value, without converting it').
rule_description('rule-key-arguments-missing', 'Advisory: an opposing rule pair stays unresolved only because a body predicate declares no key_arguments; the finding names the predicate and the key positions that would decide the pair').
rule_description('domain-contradictions', 'Detect contradictions between requirements constraining the same fact').
rule_description('logic-coverage', 'Require every explicitly declared atomic requirement claim to be grounded by a linked strict-property or predicate fact').
rule_description('rule-safety', 'Stored Logic IR rules use only the typed, bounded, stratified vocabulary').
rule_description('rule-verifiability', 'Requirement rule links resolve to safe rules and registered rule schemas').
rule_description('query-plan-safety', 'Detect Prolog validation clauses that place negation before generator calls').
rule_description('req-status-vocabulary', 'Requirement statuses must use the canonical vocabulary (open, in_progress, closed; legacy: active, approved); ADR statuses such as accepted silently fall out of the proof ladder').
rule_description('strict-fact-shape', 'Detect malformed strict facts (facts with fact_kind that are missing required fields)').
rule_description('strict-req-fact-pairing', 'Detect requirements with incomplete strict subject/property fact pairing for contradiction-safe semantics').
rule_description('predicate-verifiability', 'Detect requires_predicate links that do not target ground fact_kind: predicate facts').
rule_description('strict-readiness', 'Report strict contradiction-readiness levels for requirements that are still prose-only or otherwise not contradiction-ready').
rule_description('semantic-completeness', 'Every inventoried assertive proposition is modeled or explicitly classified').
rule_description('proof-contract-symbols', 'Detect unresolved required_proofs.symbol_id values, type-shape required proofs, and proof_bindings.source_file disagreement with the named symbol sourceFile').
rule_description('entity-id-style', 'Entity IDs name the governed behavior and match their filename stem; new purely numeric IDs are reported at creation boundaries').
rule_description('domain-redundancy', 'Two current requirements must not ground the identical logical term or share a ground fact unless linked by supersedes or restates').
rule_description('domain-implication', 'Informational: one requirement\'s numeric bound strictly implies another requirement\'s bound on the same subject and property').
rule_description('subject-key-identity', 'Subject keys must name a shared component, not be derived from a requirement ID').
rule_description('subject-key-shape', 'Subject keys follow dotted component.aspect[.sub] with lowercase snake segments').
rule_description('ontology-quality', 'Informational: predicate schemas whose argument values mostly occur in only one fact are carrying prose instead of a shared vocabulary').
rule_description('exception-unapproved', 'Advisory: a current exception requirement exempts another requirement but has no approved_by, so it exempts nothing until a human approves it').
rule_description('exception-approval-self-attested', 'Advisory: an agent-authored exception records approved_by but no human corroborated it (origin.approved_by or approval_ref is missing), so a human should confirm the approval').
rule_description('agent-requirement-unapproved', 'Informational: current requirements authored by an agent (origin.kind agent) that no human has approved (origin.approved_by), listed up to 25 per check').
rule_description('predicate-schema-conformance', 'Predicate facts match a predicate_schema (project-local, or the built-in catalog in the default namespace) and use its declared argument constants').
