% Module: symbol_classification
% GENERATED by scripts/generate-symbol-classification.mjs from
% packages/core/schema/symbol-classification.json. Do not edit directly.
%
% Vocabulary facts shared by TS and Prolog so symbol classification cannot
% drift between the extractors, the manifest gate, and validation.

:- module(symbol_classification, [
    allowed_granularity_reason/1,
    coarse_granularity_reason/1,
    symbol_role/1,
    inferred_role/2,
    traceability_relationship_type/1
]).

allowed_granularity_reason('config-artifact').
allowed_granularity_reason('module-level-behavior').
allowed_granularity_reason('extractor-miss').
allowed_granularity_reason('legacy-link').
allowed_granularity_reason('test-suite').

coarse_granularity_reason('config-artifact').
coarse_granularity_reason('module-level-behavior').
coarse_granularity_reason('extractor-miss').
coarse_granularity_reason('test-suite').

symbol_role('behavioral').
symbol_role('structural').
symbol_role('type-shape').
symbol_role('config').
symbol_role('module').
symbol_role('unknown').

inferred_role('function', 'behavioral').
inferred_role('class', 'behavioral').
inferred_role('method', 'behavioral').
inferred_role('property', 'behavioral').
inferred_role('accessor', 'behavioral').
inferred_role('interface', 'type-shape').
inferred_role('type', 'type-shape').
inferred_role('enum', 'type-shape').
inferred_role('variable', 'unknown').
inferred_role('unknown', 'unknown').

traceability_relationship_type('implements').
traceability_relationship_type('covered_by').
traceability_relationship_type('executable_for').
