import type { PredicateSchemaCandidate } from "./predicate-types.js";

// implements REQ-mcp-suggest-predicates
export const PREDICATE_CATALOG_4: PredicateSchemaCandidate[] = [
  {
    id: "FACT-SCHEMA-DEPENDENCY-RESOLUTION-POLICY",
    predicate_name: "dependency_resolution_policy",
    title: "Dependency resolution policy",
    description:
      "Defines where a component may resolve a dependency and how it may acquire it.",
    argument_names: [
      "component",
      "dependency",
      "allowed_scope",
      "acquisition_policy",
    ],
    argument_types: ["component", "dependency", "scope", "policy"],
    argument_descriptions: [
      "Component performing resolution.",
      "Dependency to resolve.",
      "Permitted resolution scope.",
      "Allowed acquisition behavior.",
    ],
    keywords: [
      "dependency",
      "resolve",
      "resolution",
      "local",
      "workspace",
      "download",
      "acquire",
    ],
    aliases: ["dependency lookup policy", "dependency acquisition policy"],
    examples: [
      "dependency_resolution_policy(plugin_launcher, mcp_server, consumer_local, no_download)",
    ],
    tags: ["dependency", "resolution", "policy"],
  },
  {
    id: "FACT-SCHEMA-ORDERED-RESOLUTION-STRATEGY",
    predicate_name: "ordered_resolution_strategy",
    title: "Ordered resolution strategy",
    description:
      "Defines ordered sources for resolving a dependency and the condition for fallback.",
    argument_names: ["resolver", "ordered_sources", "fallback_condition"],
    argument_types: ["component", "source_list", "condition"],
    argument_descriptions: [
      "Resolver applying the strategy.",
      "Sources tried in order.",
      "Condition permitting fallback.",
    ],
    keywords: [
      "ordered",
      "first",
      "then",
      "fallback",
      "candidate",
      "workspace",
      "cwd",
    ],
    aliases: ["ordered lookup", "resolution fallback order"],
    examples: [
      "ordered_resolution_strategy(launcher, workspace_node_modules|root_node_modules, missing_candidate)",
    ],
    tags: ["resolution", "ordering", "fallback"],
  },
  {
    id: "FACT-SCHEMA-RESOLUTION-FAILURE-POLICY",
    predicate_name: "resolution_failure_policy",
    title: "Resolution failure policy",
    description:
      "Defines the required outcome when dependency resolution encounters invalid or ambiguous inputs.",
    argument_names: ["resolver", "invalid_condition", "required_outcome"],
    argument_types: ["component", "condition", "outcome"],
    argument_descriptions: [
      "Resolver enforcing the policy.",
      "Invalid or ambiguous condition.",
      "Required failure outcome.",
    ],
    keywords: [
      "invalid",
      "ambiguous",
      "reject",
      "resolution",
      "error",
      "fail clearly",
    ],
    aliases: ["invalid resolution handling", "resolution rejection policy"],
    examples: [
      "resolution_failure_policy(launcher, invalid_placeholder, clear_error)",
    ],
    tags: ["resolution", "failure", "validation"],
  },
  {
    id: "FACT-SCHEMA-PROCESS-DELEGATION-CONTRACT",
    predicate_name: "process_delegation_contract",
    title: "Process delegation contract",
    description:
      "Defines executable, working-directory, environment, stdio, and termination behavior for a delegated child process.",
    argument_names: [
      "launcher",
      "executable_policy",
      "cwd_policy",
      "environment_policy",
      "stdio_policy",
      "termination_policy",
    ],
    argument_types: [
      "component",
      "policy",
      "policy",
      "policy",
      "policy",
      "policy",
    ],
    argument_descriptions: [
      "Launcher delegating the process.",
      "Executable selection policy.",
      "Working-directory policy.",
      "Environment policy.",
      "Standard I/O policy.",
      "Termination and exit propagation policy.",
    ],
    keywords: [
      "child process",
      "spawn",
      "executable",
      "cwd",
      "environment",
      "stdio",
      "terminate",
    ],
    aliases: ["child process contract", "process launch contract"],
    examples: [
      "process_delegation_contract(launcher, resolved_executable, consumer_cwd, inherited_env, piped_stdio, propagate_exit)",
    ],
    tags: ["process", "execution", "contract"],
  },
  {
    id: "FACT-SCHEMA-FAILURE-BEHAVIOR",
    predicate_name: "failure_behavior",
    title: "Failure behavior",
    description:
      "Defines the required outcome when a component encounters a named failure condition.",
    argument_names: ["component", "failure_condition", "required_outcome"],
    argument_types: ["component", "condition", "outcome"],
    argument_descriptions: [
      "Component experiencing failure.",
      "Failure condition.",
      "Required observable outcome.",
    ],
    keywords: [
      "missing dependency",
      "failure",
      "error",
      "must report",
      "required outcome",
    ],
    aliases: ["failure handling", "error behavior"],
    examples: [
      "failure_behavior(plugin_launcher, missing_dependency, actionable_error)",
    ],
    tags: ["failure", "error", "behavior"],
  },
  {
    id: "FACT-SCHEMA-FEATURE-GATE",
    predicate_name: "feature_gate",
    title: "Feature gate",
    description: "A subject is controlled by a runtime or configuration gate.",
    argument_names: ["subject", "gate", "expected"],
    argument_types: ["entity", "flag", "boolean"],
    keywords: ["flag", "feature gate", "enabled", "disabled", "kill switch"],
    examples: ["feature_gate(checkout.v2, checkoutV2Enabled, true)"],
    tags: ["flag", "runtime"],
  },
  {
    id: "FACT-SCHEMA-EVENT-PUBLISH",
    predicate_name: "publishes_event",
    title: "Event publication",
    description: "A subject publishes a domain or system event.",
    argument_names: ["subject", "event"],
    argument_types: ["entity", "event"],
    keywords: ["publish", "publishes", "emit", "emits", "event"],
    examples: ["publishes_event(order.checkout, OrderSubmitted)"],
    tags: ["event", "architecture"],
  },
  {
    id: "FACT-SCHEMA-ACCEPTANCE-RULE",
    predicate_name: "acceptance_rule",
    title: "Acceptance rule",
    description: "A subject has an observable acceptance outcome.",
    argument_names: ["subject", "outcome"],
    argument_types: ["entity", "outcome"],
    keywords: [
      "acceptance",
      "observable",
      "outcome",
      "must show",
      "must display",
    ],
    examples: ["acceptance_rule(search.results, shows_empty_state)"],
    tags: ["acceptance", "quality"],
  },
  {
    id: "FACT-SCHEMA-PERMISSION-RULE",
    predicate_name: "permission_rule",
    title: "Permission rule",
    description: "An actor is allowed or denied an action against a resource.",
    argument_names: ["actor", "action", "resource", "decision"],
    argument_types: ["actor", "action", "resource", "decision"],
    keywords: [
      "may",
      "can",
      "allowed",
      "denied",
      "forbidden",
      "must not",
      "cannot",
      "can't",
      "export",
      "permission",
    ],
    examples: ["permission_rule(guest, export, customer_data, deny)"],
    tags: ["permission", "policy"],
  },
  {
    id: "FACT-SCHEMA-DEFAULT-VALUE",
    predicate_name: "default_value",
    title: "Default value",
    description: "A subject property defaults to a value.",
    argument_names: ["subject", "property", "value"],
    argument_types: ["entity", "property", "value"],
    keywords: ["default", "defaults", "defaulted", "initial", "mode", "tool"],
    examples: ["default_value(annotation.tool, mode, move)"],
    tags: ["default", "configuration"],
  },
  {
    id: "FACT-SCHEMA-UNIQUENESS-CONSTRAINT",
    predicate_name: "uniqueness_constraint",
    title: "Uniqueness constraint",
    description: "A subject is unique within one or more scope keys.",
    argument_names: ["subject", "scope"],
    argument_types: ["entity", "scope"],
    keywords: ["unique", "uniqueness", "at most one", "one", "per"],
    examples: ["uniqueness_constraint(annotation, video,timeKey)"],
    tags: ["constraint", "identity"],
  },
  {
    id: "FACT-SCHEMA-STATE-MEMBERSHIP",
    predicate_name: "state_membership",
    title: "State membership",
    description: "A state-valued subject has a closed set of allowed states.",
    argument_names: ["subject", "states"],
    argument_types: ["entity", "state_list"],
    keywords: ["terminal states", "states are", "one of", "ready", "anonymous"],
    examples: ["state_membership(auth.status, ready,anonymous,profile-error)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-TEMPORAL-ORDER",
    predicate_name: "temporal_order",
    title: "Temporal order",
    description: "One event or state must occur before or after another.",
    argument_names: ["subject", "before_event", "after_event"],
    argument_types: ["entity", "event", "event"],
    keywords: ["before", "after", "saved", "completes", "navigation"],
    examples: ["temporal_order(draft.changes, saved, navigation_completes)"],
    tags: ["temporal", "workflow"],
  },
  {
    id: "FACT-SCHEMA-CONDITIONAL-BEHAVIOR",
    predicate_name: "conditional_behavior",
    title: "Conditional behavior",
    description: "A behavior follows when a condition is true.",
    argument_names: ["subject", "condition", "behavior"],
    argument_types: ["entity", "condition", "behavior"],
    keywords: ["if", "during", "becomes", "condition", "provided that"],
    examples: [
      "conditional_behavior(card, fails_during_session, becomes_tainted)",
    ],
    tags: ["conditional", "workflow"],
  },
  {
    id: "FACT-SCHEMA-STATE-TRANSITION",
    predicate_name: "state_transition",
    title: "State transition",
    description:
      "A subject moves from one state to another because of a trigger.",
    argument_names: ["subject", "from_state", "to_state", "trigger"],
    argument_types: ["entity", "state", "state", "trigger"],
    keywords: ["transitions from", "transition from", "from draft", "to idle"],
    examples: ["state_transition(editor, draft, idle, navigation_completes)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-RATE-LIMIT",
    predicate_name: "rate_limit",
    title: "Rate limit",
    description: "An action is limited to a count within a time window.",
    argument_names: ["subject", "action", "window", "count"],
    argument_types: ["entity", "action", "duration", "number"],
    keywords: [
      "rate limited",
      "rate limit",
      "attempts",
      "per hour",
      "per minute",
    ],
    examples: ["rate_limit(password_reset.request, attempts, hour, 5)"],
    tags: ["rate-limit", "security"],
  },
];
