import type { PredicateSchemaCandidate } from "./predicate-types.js";

// implements REQ-mcp-suggest-predicates
export const PREDICATE_CATALOG_3: PredicateSchemaCandidate[] = [
  {
    id: "FACT-SCHEMA-ORDERED-STRATEGY-RULE",
    predicate_name: "ordered_strategy_rule",
    title: "Ordered strategy rule",
    description: "A subject must use strategies in a required priority order.",
    argument_names: ["subject", "strategy_kind", "ordered_values"],
    argument_types: ["entity", "strategy_kind", "ordered_list"],
    keywords: ["priority order", "selector strategies", "fallback order"],
    examples: [
      "ordered_strategy_rule(poms, selector_strategies, data-testid,visible,text)",
    ],
    tags: ["strategy", "priority"],
  },
  {
    id: "FACT-SCHEMA-REFRESH-POLICY-RULE",
    predicate_name: "refresh_policy_rule",
    title: "Refresh policy rule",
    description:
      "A subject refreshes a target automatically or by a named policy.",
    argument_names: ["subject", "target", "policy"],
    argument_types: ["entity", "target", "policy"],
    keywords: ["automatically refresh", "manual page reload", "refresh"],
    examples: ["refresh_policy_rule(dashboard, processing_videos, automatic)"],
    tags: ["refresh", "ui"],
  },
  {
    id: "FACT-SCHEMA-SCOPED-AUTHORIZATION-RULE",
    predicate_name: "scoped_authorization_rule",
    title: "Scoped authorization rule",
    description:
      "A scoped actor is allowed or denied an action because of assignment, ownership, or membership.",
    argument_names: ["actor_scope", "action", "decision"],
    argument_types: ["actor_scope", "action", "decision"],
    keywords: ["unassigned", "assigned", "denied", "scoped"],
    examples: [
      "scoped_authorization_rule(unassigned_instructors, signed_url_generation, deny)",
    ],
    tags: ["authorization", "scope"],
  },
  {
    id: "FACT-SCHEMA-DOCUMENTATION-STANDARD-RULE",
    predicate_name: "documentation_standard_rule",
    title: "Documentation standard rule",
    description:
      "A subject must be documented in a named documentation artifact.",
    argument_names: ["subject", "relation", "artifact"],
    argument_types: ["entity", "relation", "artifact"],
    keywords: ["documented", "docs", "symbols", "documentation"],
    examples: [
      "documentation_standard_rule(code_symbols, documented_in, docs_symbols_yaml)",
    ],
    tags: ["documentation", "standard"],
  },
  {
    id: "FACT-SCHEMA-WARMUP-POLICY-RULE",
    predicate_name: "warmup_policy_rule",
    title: "Warmup policy rule",
    description: "A subject must warm up on a named trigger or entry point.",
    argument_names: ["subject", "trigger"],
    argument_types: ["entity", "trigger"],
    keywords: ["warm up", "warmup", "on entry"],
    examples: ["warmup_policy_rule(editor_video, entry)"],
    tags: ["warmup", "performance"],
  },
  {
    id: "FACT-SCHEMA-VISUAL-LAYOUT-RULE",
    predicate_name: "visual_layout_rule",
    title: "Visual layout rule",
    description:
      "A UI subject must remain visually aligned or layout-consistent with a target.",
    argument_names: ["subject", "relation", "target"],
    argument_types: ["ui_entity", "relation", "ui_entity"],
    keywords: ["visually aligned", "layout", "aligned with"],
    examples: [
      "visual_layout_rule(processing_video_cards, aligned_with, ready_cards)",
    ],
    tags: ["visual", "layout"],
  },
  {
    id: "FACT-SCHEMA-ENFORCEMENT-LOCATION-RULE",
    predicate_name: "enforcement_location_rule",
    title: "Enforcement location rule",
    description:
      "A constraint or policy must be enforced at a named system layer.",
    argument_names: ["subject", "location"],
    argument_types: ["constraint", "system_layer"],
    keywords: ["enforced at", "database level", "application level"],
    examples: [
      "enforcement_location_rule(foreign_key_constraints, database_level)",
    ],
    tags: ["enforcement", "architecture"],
  },
  {
    id: "FACT-SCHEMA-RECONCILIATION-RULE",
    predicate_name: "reconciliation_rule",
    title: "Reconciliation rule",
    description:
      "A trigger reconciles a target and performs a stale-data cleanup action.",
    argument_names: ["subject", "trigger", "target", "action"],
    argument_types: ["entity", "trigger", "target", "action"],
    keywords: ["reconcile", "clear stale", "stale notifications"],
    examples: [
      "reconciliation_rule(system, login, analysis_notifications, clear_stale_notifications)",
    ],
    tags: ["reconciliation", "cleanup"],
  },
  {
    id: "FACT-SCHEMA-THROTTLE-POLICY-RULE",
    predicate_name: "throttle_policy_rule",
    title: "Throttle policy rule",
    description:
      "Handlers or operations must be throttled for a named activity class.",
    argument_names: ["subject", "condition"],
    argument_types: ["entity", "condition"],
    keywords: ["throttled", "high-frequency", "event handlers"],
    examples: [
      "throttle_policy_rule(event_handlers, high-frequency_operations)",
    ],
    tags: ["throttle", "performance"],
  },
  {
    id: "FACT-SCHEMA-HAS-UNSAVED-CHANGES",
    predicate_name: "has_unsaved_changes",
    title: "Unsaved change state",
    description: "A subject has unsaved or dirty local edits.",
    argument_names: ["subject", "expected"],
    argument_types: ["entity", "boolean"],
    keywords: ["unsaved", "dirty", "draft", "edits", "changes"],
    examples: ["has_unsaved_changes(editor.annotation, true)"],
    tags: ["state", "persistence"],
  },
  {
    id: "FACT-SCHEMA-COMMIT-ACTION",
    predicate_name: "commit_action",
    title: "Commit or save action",
    description:
      "A trigger commits, saves, or persists a subject within a scope.",
    argument_names: ["subject", "trigger", "scope"],
    argument_types: ["entity", "trigger", "scope"],
    keywords: [
      "save",
      "saves",
      "saved",
      "auto-save",
      "autosave",
      "commit",
      "persist",
      "navigation",
      "navigates",
      "draft",
    ],
    examples: ["commit_action(editor.annotation, navigation, draft)"],
    tags: ["persistence", "workflow"],
  },
  {
    id: "FACT-SCHEMA-DISCARD-ACTION",
    predicate_name: "discard_action",
    title: "Discard action",
    description:
      "A trigger discards or cancels changes for a subject within a scope.",
    argument_names: ["subject", "trigger", "scope"],
    argument_types: ["entity", "trigger", "scope"],
    keywords: ["discard", "cancel", "escape", "revert", "without save"],
    examples: ["discard_action(editor.annotation, escape, active_annotation)"],
    tags: ["persistence", "workflow"],
  },
  {
    id: "FACT-SCHEMA-ACCESSIBILITY",
    predicate_name: "accessibility_requirement",
    title: "Accessibility requirement",
    description:
      "A subject must satisfy an accessibility standard or severity target.",
    argument_names: ["subject", "standard", "severity"],
    argument_types: ["entity", "standard", "severity"],
    keywords: ["accessibility", "a11y", "wcag", "keyboard", "screen reader"],
    examples: ["accessibility_requirement(game.flow, WCAG, high)"],
    tags: ["accessibility", "quality"],
  },
  {
    id: "FACT-SCHEMA-RETENTION-POLICY",
    predicate_name: "retention_policy",
    title: "Retention policy",
    description: "A subject is retained for a bounded duration.",
    argument_names: ["subject", "duration", "unit"],
    argument_types: ["entity", "number", "unit"],
    keywords: ["retain", "retained", "retention", "days", "months", "years"],
    examples: ["retention_policy(customer.data, 7, years)"],
    tags: ["data", "policy"],
  },
  {
    id: "FACT-SCHEMA-RESOURCE-CONSTRAINT",
    predicate_name: "resource_constraint",
    title: "Resource constraint",
    description:
      "A subject constrains a resource by operator, threshold, and unit.",
    argument_names: ["subject", "resource", "operator", "threshold", "unit"],
    argument_types: ["entity", "resource", "operator", "number", "unit"],
    keywords: [
      "limit",
      "maximum",
      "minimum",
      "latency",
      "timeout",
      "size",
      "fps",
      "frame rate",
      "complete in",
      "time budget",
    ],
    paraphrase_templates: [
      "must complete in under a bounded duration",
      "must stay at a bounded frame rate",
      "must respond within a time budget",
    ],
    examples: ["resource_constraint(api.search, latency, lte, 200, ms)"],
    tags: ["performance", "constraint"],
  },
];
