import type { PredicateSchemaCandidate } from "./predicate-types.js";

// implements REQ-mcp-suggest-predicates
export const PREDICATE_CATALOG_4: PredicateSchemaCandidate[] = [
  {
    id: "FACT-SCHEMA-FEATURE-GATE",
    predicate_name: "feature_gate",
    title: "Feature gate",
    description: "A subject is controlled by a runtime or configuration gate.",
    argument_names: ["subject", "gate", "expected"],
    argument_types: ["entity", "flag", "boolean"],
    keywords: ["flag", "feature gate", "enabled", "disabled", "kill switch"],
    examples: ["feature_gate(checkout.v2, checkoutV2Enabled, true)"],
    tags: ["flag", "runtime"],
  },
  {
    id: "FACT-SCHEMA-EVENT-PUBLISH",
    predicate_name: "publishes_event",
    title: "Event publication",
    description: "A subject publishes a domain or system event.",
    argument_names: ["subject", "event"],
    argument_types: ["entity", "event"],
    keywords: ["publish", "publishes", "emit", "emits", "event"],
    examples: ["publishes_event(order.checkout, OrderSubmitted)"],
    tags: ["event", "architecture"],
  },
  {
    id: "FACT-SCHEMA-ACCEPTANCE-RULE",
    predicate_name: "acceptance_rule",
    title: "Acceptance rule",
    description: "A subject has an observable acceptance outcome.",
    argument_names: ["subject", "outcome"],
    argument_types: ["entity", "outcome"],
    keywords: [
      "acceptance",
      "observable",
      "outcome",
      "must show",
      "must display",
    ],
    examples: ["acceptance_rule(search.results, shows_empty_state)"],
    tags: ["acceptance", "quality"],
  },
  {
    id: "FACT-SCHEMA-PERMISSION-RULE",
    predicate_name: "permission_rule",
    title: "Permission rule",
    description: "An actor is allowed or denied an action against a resource.",
    argument_names: ["actor", "action", "resource", "decision"],
    argument_types: ["actor", "action", "resource", "decision"],
    keywords: [
      "may",
      "can",
      "allowed",
      "denied",
      "forbidden",
      "must not",
      "cannot",
      "can't",
      "export",
      "permission",
    ],
    examples: ["permission_rule(guest, export, customer_data, deny)"],
    tags: ["permission", "policy"],
  },
  {
    id: "FACT-SCHEMA-DEFAULT-VALUE",
    predicate_name: "default_value",
    title: "Default value",
    description: "A subject property defaults to a value.",
    argument_names: ["subject", "property", "value"],
    argument_types: ["entity", "property", "value"],
    keywords: ["default", "defaults", "defaulted", "initial", "mode", "tool"],
    examples: ["default_value(annotation.tool, mode, move)"],
    tags: ["default", "configuration"],
  },
  {
    id: "FACT-SCHEMA-UNIQUENESS-CONSTRAINT",
    predicate_name: "uniqueness_constraint",
    title: "Uniqueness constraint",
    description: "A subject is unique within one or more scope keys.",
    argument_names: ["subject", "scope"],
    argument_types: ["entity", "scope"],
    keywords: ["unique", "uniqueness", "at most one", "one", "per"],
    examples: ["uniqueness_constraint(annotation, video,timeKey)"],
    tags: ["constraint", "identity"],
  },
  {
    id: "FACT-SCHEMA-STATE-MEMBERSHIP",
    predicate_name: "state_membership",
    title: "State membership",
    description: "A state-valued subject has a closed set of allowed states.",
    argument_names: ["subject", "states"],
    argument_types: ["entity", "state_list"],
    keywords: ["terminal states", "states are", "one of", "ready", "anonymous"],
    examples: ["state_membership(auth.status, ready,anonymous,profile-error)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-TEMPORAL-ORDER",
    predicate_name: "temporal_order",
    title: "Temporal order",
    description: "One event or state must occur before or after another.",
    argument_names: ["subject", "before_event", "after_event"],
    argument_types: ["entity", "event", "event"],
    keywords: ["before", "after", "saved", "completes", "navigation"],
    examples: ["temporal_order(draft.changes, saved, navigation_completes)"],
    tags: ["temporal", "workflow"],
  },
  {
    id: "FACT-SCHEMA-CONDITIONAL-BEHAVIOR",
    predicate_name: "conditional_behavior",
    title: "Conditional behavior",
    description: "A behavior follows when a condition is true.",
    argument_names: ["subject", "condition", "behavior"],
    argument_types: ["entity", "condition", "behavior"],
    keywords: ["if", "during", "becomes", "condition", "provided that"],
    examples: [
      "conditional_behavior(card, fails_during_session, becomes_tainted)",
    ],
    tags: ["conditional", "workflow"],
  },
  {
    id: "FACT-SCHEMA-STATE-TRANSITION",
    predicate_name: "state_transition",
    title: "State transition",
    description:
      "A subject moves from one state to another because of a trigger.",
    argument_names: ["subject", "from_state", "to_state", "trigger"],
    argument_types: ["entity", "state", "state", "trigger"],
    keywords: ["transitions from", "transition from", "from draft", "to idle"],
    examples: ["state_transition(editor, draft, idle, navigation_completes)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-RATE-LIMIT",
    predicate_name: "rate_limit",
    title: "Rate limit",
    description: "An action is limited to a count within a time window.",
    argument_names: ["subject", "action", "window", "count"],
    argument_types: ["entity", "action", "duration", "number"],
    keywords: [
      "rate limited",
      "rate limit",
      "attempts",
      "per hour",
      "per minute",
    ],
    examples: ["rate_limit(password_reset.request, attempts, hour, 5)"],
    tags: ["rate-limit", "security"],
  },
];
