import type { PredicateSchemaCandidate } from "./predicate-types.js";

// implements REQ-mcp-suggest-predicates
export const PREDICATE_CATALOG_1: PredicateSchemaCandidate[] = [
  {
    id: "FACT-SCHEMA-STATE",
    predicate_name: "state",
    title: "State assertion",
    description: "A subject has or enters a named state.",
    argument_names: ["subject", "state"],
    argument_types: ["entity", "state"],
    keywords: ["state", "mode", "idle", "active", "draft", "edit"],
    examples: ["state(editor.annotation, idle)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-TRANSITION",
    predicate_name: "transition",
    title: "State transition",
    description: "A subject transitions between states because of a trigger.",
    argument_names: ["subject", "from_state", "to_state", "trigger"],
    argument_types: ["entity", "state", "state", "trigger"],
    keywords: [
      "transition",
      "enter",
      "leave",
      "idle",
      "navigate",
      "navigates",
      "cancel",
      "escape",
    ],
    examples: ["transition(editor.annotation, draft, idle, navigation)"],
    tags: ["state", "workflow"],
  },
  {
    id: "FACT-SCHEMA-GUARD",
    predicate_name: "guard",
    title: "Behavior guard",
    description: "A condition gates or forbids behavior for a subject.",
    argument_names: ["subject", "condition", "expected"],
    argument_types: ["entity", "condition", "boolean"],
    keywords: ["guard", "unless", "readonly", "scrubbing", "disabled until"],
    examples: ["guard(editor.annotation, isReadOnly, false)"],
    tags: ["guard", "workflow"],
  },
  {
    id: "FACT-SCHEMA-EXCEPTION-RULE",
    predicate_name: "exception_rule",
    title: "Exception rule",
    description:
      "A required behavior is skipped when a named exception condition holds.",
    argument_names: ["subject", "behavior", "exception"],
    argument_types: ["entity", "behavior", "condition"],
    keywords: ["unless", "except", "except when", "opted out", "exception"],
    examples: [
      "exception_rule(notification.service, send_email, user_has_opted_out)",
    ],
    tags: ["exception", "conditional"],
  },
  {
    id: "FACT-SCHEMA-MUTUAL-EXCLUSION",
    predicate_name: "mutual_exclusion",
    title: "Mutual exclusion",
    description:
      "Two modes, states, options, or behaviors cannot be true or active together.",
    argument_names: ["left", "right"],
    argument_types: ["entity", "entity"],
    keywords: ["mutually exclusive", "exclusive", "cannot overlap", "not both"],
    examples: ["mutual_exclusion(practice_mode, exam_mode)"],
    tags: ["constraint", "exclusivity"],
  },
  {
    id: "FACT-SCHEMA-DEPENDENCY-RULE",
    predicate_name: "dependency_rule",
    title: "Dependency rule",
    description:
      "A subject requires a prerequisite before a dependent action or state can proceed.",
    argument_names: ["subject", "prerequisite", "dependent"],
    argument_types: ["entity", "condition", "action"],
    keywords: ["requires", "depends on", "prerequisite", "before"],
    examples: [
      "dependency_rule(checkout, payment_authorization, order_submission)",
    ],
    tags: ["dependency", "workflow"],
  },
  {
    id: "FACT-SCHEMA-OWNERSHIP-RULE",
    predicate_name: "ownership_rule",
    title: "Ownership rule",
    description:
      "A resource or behavior is owned by a service, team, role, or component.",
    argument_names: ["resource", "owner"],
    argument_types: ["entity", "owner"],
    keywords: ["owned by", "owner", "responsible for"],
    examples: ["ownership_rule(account_settings, profile_service)"],
    tags: ["ownership", "governance"],
  },
  {
    id: "FACT-SCHEMA-RETRY-POLICY",
    predicate_name: "retry_policy",
    title: "Retry policy",
    description:
      "A failed subject or action retries up to a bounded attempt count.",
    argument_names: ["subject", "count", "unit"],
    argument_types: ["entity", "number", "unit"],
    keywords: ["retry", "retries", "up to", "attempts", "times"],
    examples: ["retry_policy(failed_webhook_delivery, 3, times)"],
    tags: ["retry", "resilience"],
  },
  {
    id: "FACT-SCHEMA-ESCALATION-RULE",
    predicate_name: "escalation_rule",
    title: "Escalation rule",
    description:
      "A failed or unresolved subject escalates to an owner after a bounded delay.",
    argument_names: ["subject", "target", "delay", "unit"],
    argument_types: ["entity", "owner", "number", "unit"],
    keywords: ["escalate", "escalates", "escalation", "after", "support"],
    examples: ["escalation_rule(failed_payment_disputes, support, 48, hours)"],
    tags: ["escalation", "operations"],
  },
  {
    id: "FACT-SCHEMA-AVAILABILITY-SLA",
    predicate_name: "availability_sla",
    title: "Availability SLA",
    description:
      "A service or API must meet a minimum availability target over a reporting window.",
    argument_names: ["subject", "threshold", "unit", "window"],
    argument_types: ["entity", "number", "unit", "duration"],
    keywords: ["availability", "at least", "percent", "monthly", "sla"],
    examples: ["availability_sla(checkout_api, 99.9, percent, monthly)"],
    tags: ["sla", "availability"],
  },
  {
    id: "FACT-SCHEMA-NOTIFICATION-ROUTE",
    predicate_name: "notification_route",
    title: "Notification route",
    description:
      "A subject notifies a target recipient through a specific channel.",
    argument_names: ["subject", "recipient", "channel"],
    argument_types: ["entity", "recipient", "channel"],
    keywords: ["notify", "notifies", "notification", "by email", "by sms"],
    examples: ["notification_route(fraud_alerts, risk_operations, email)"],
    tags: ["notification", "routing"],
  },
  {
    id: "FACT-SCHEMA-IDEMPOTENCY-RULE",
    predicate_name: "idempotency_rule",
    title: "Idempotency rule",
    description:
      "A request or operation must deduplicate repeated execution by a stable idempotency key.",
    argument_names: ["subject", "key"],
    argument_types: ["entity", "key"],
    keywords: [
      "idempotent",
      "idempotency",
      "idempotency key",
      "dedupe",
      "deduplicated",
      "redundant",
      "concurrent",
    ],
    examples: ["idempotency_rule(payment_capture_requests, idempotency_key)"],
    tags: ["idempotency", "resilience"],
  },
  {
    id: "FACT-SCHEMA-DATA-RESIDENCY-RULE",
    predicate_name: "data_residency_rule",
    title: "Data residency rule",
    description:
      "A data set must be stored, processed, or kept within a named region or jurisdiction.",
    argument_names: ["subject", "region"],
    argument_types: ["entity", "region"],
    keywords: ["data residency", "stored in", "region", "jurisdiction"],
    examples: ["data_residency_rule(eu_customer_data, eu_region)"],
    tags: ["privacy", "data-residency"],
  },
  {
    id: "FACT-SCHEMA-AUDIT-EVENT-RULE",
    predicate_name: "audit_event_rule",
    title: "Audit event rule",
    description:
      "An action, change, or security-relevant event must be recorded in an audit log or audit trail.",
    argument_names: ["subject", "log"],
    argument_types: ["entity", "log"],
    keywords: ["audit log", "audit trail", "recorded", "logged", "audited"],
    examples: ["audit_event_rule(admin_access_changes, audit_log)"],
    tags: ["audit", "logging", "governance"],
  },
  {
    id: "FACT-SCHEMA-CONSENT-RULE",
    predicate_name: "consent_rule",
    title: "Consent rule",
    description:
      "An action or processing purpose requires a named consent before it proceeds.",
    argument_names: ["subject", "consent", "purpose"],
    argument_types: ["entity", "consent", "purpose"],
    keywords: ["consent", "requires consent", "before processing"],
    examples: ["consent_rule(marketing_emails, user_consent, processing)"],
    tags: ["privacy", "consent"],
  },
  {
    id: "FACT-SCHEMA-LIFECYCLE-RULE",
    predicate_name: "lifecycle_rule",
    title: "Lifecycle rule",
    description:
      "An entity must be archived, deleted, expired, or lifecycle-transitioned after a duration.",
    argument_names: ["subject", "action", "duration", "unit"],
    argument_types: ["entity", "action", "number", "unit"],
    keywords: ["archive", "archived", "delete", "deleted", "expire", "after"],
    examples: ["lifecycle_rule(expired_sessions, archived, 30, days)"],
    tags: ["lifecycle", "retention"],
  },
];
