/*
 * Kibi — repo-local, per-branch, queryable long-term memory for software projects
 * Copyright (C) 2026 Piotr Franczyk
 *
 * This file is generated by scripts/generate-rule-registry.mjs from
 * packages/core/schema/rule-registry.json. Do not edit it directly; edit the
 * JSON source and regenerate.
 */

// implements REQ-006
export const GENERATED_RULES = [
  {
    name: "must-priority-coverage",
    description: "Every must-priority requirement must have a scenario and a test",
    enforcementClass: "canonical",
    category: "coverage",
  },
  {
    name: "symbol-coverage",
    description: "Production symbols need qualifying coverage via covered_by plus a canonical requirement/scenario test path",
    enforcementClass: "canonical",
    category: "coverage",
  },
  {
    name: "symbol-traceability",
    description: "Production symbols must directly implement requirements for ownership; covered_by is coverage only and executable_for is test identity only",
    enforcementClass: "canonical",
    category: "traceability",
  },
  {
    name: "no-dangling-refs",
    description: "All relationship targets must exist in the KB",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "source-relationship-parity",
    description: "Authored Markdown and relationship-shard edges must exactly match the compiled KB",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "no-cycles",
    description: "No circular dependency chains in requirements",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "required-fields",
    description: "All entities must have required fields",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "deprecated-adr-no-successor",
    description: "Deprecated ADRs must have a successor ADR that supersedes them",
    enforcementClass: "canonical",
    category: "lifecycle",
  },
  {
    name: "domain-contradictions",
    description: "Detect contradictions between requirements constraining the same fact",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "logic-coverage",
    description: "Require every explicitly declared atomic requirement claim to be grounded by a linked strict-property or predicate fact",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "rule-safety",
    description: "Stored Logic IR rules use only the typed, bounded, stratified vocabulary",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "rule-verifiability",
    description: "Requirement rule links resolve to safe rules and registered rule schemas",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "query-plan-safety",
    description: "Detect Prolog validation clauses that place negation before generator calls",
    enforcementClass: "canonical",
    category: "integrity",
  },
  {
    name: "req-status-vocabulary",
    description: "Requirement statuses must use the canonical vocabulary (open, in_progress, closed; legacy: active, approved); ADR statuses such as accepted silently fall out of the proof ladder",
    enforcementClass: "canonical",
    category: "lifecycle",
  },
  {
    name: "strict-fact-shape",
    description: "Detect malformed strict facts (facts with fact_kind that are missing required fields)",
    enforcementClass: "advisory",
    category: "integrity",
  },
  {
    name: "strict-req-fact-pairing",
    description: "Detect requirements with incomplete strict subject/property fact pairing for contradiction-safe semantics",
    enforcementClass: "advisory",
    category: "integrity",
  },
  {
    name: "predicate-verifiability",
    description: "Detect requires_predicate links that do not target ground fact_kind: predicate facts",
    enforcementClass: "advisory",
    category: "integrity",
  },
  {
    name: "strict-readiness",
    description: "Report strict contradiction-readiness levels for requirements that are still prose-only or otherwise not contradiction-ready",
    enforcementClass: "migration",
    category: "integrity",
  },
  {
    name: "semantic-completeness",
    description: "Every inventoried assertive proposition is modeled or explicitly classified",
    enforcementClass: "migration",
    category: "integrity",
  },
] as const;
